version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000:1000"
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana:rw
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
    mem_limit: 512m
    cpu_shares: 512
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "1000:1000"
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus:/prometheus:rw
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/ || exit 1
    mem_limit: 1g
    cpu_shares: 768
    restart: unless-stopped

  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    ports:
      - "9116:9116"
    volumes:
      - ./config/snmp/snmp.yml:/etc/snmp_exporter/snmp.yml:ro
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9116/ || exit 1
    mem_limit: 256m
    cpu_shares: 512
    restart: unless-stopped

networks:
  default:
    name: monitoring
    driver: bridge

