{
 "title": "Website Monitoring Reports",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_success,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Website Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Website Uptime and SSL Expiry Overview",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"blackbox\"}[$__range]) * 100"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\"} - time()) / 3600 / 24"
    }
   ]
  },
  {
   "title": "Overall Uptime",
   "type": "gauge",
   "description": "This query calculates the average success rate of all probes under the blackbox job and multiplies it by 100 to convert it to a percentage.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job) (avg_over_time(probe_success{job=\"blackbox\"}[$__range]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{job=\"blackbox\"}[$__range]) * 100)",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "table",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Overall Average Response Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  probe_duration_seconds{\n    job=~\"$job\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}